# Generated by Django 2.2.5 on 2021-10-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardians_of_children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='violence',
            name='res',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
