# Generated by Django 2.2.5 on 2021-10-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardians_of_children', '0002_violence_res'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
            },
        ),
        migrations.RemoveField(
            model_name='violence',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='violence',
            name='res',
        ),
        migrations.RemoveField(
            model_name='violence',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='violence',
            name='title_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='violence',
            name='video_2',
            field=models.FileField(default=1, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
