# Generated by Django 2.2.5 on 2021-10-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guardians_of_children', '0004_auto_20211003_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='videos',
            new_name='video',
        ),
    ]
