# Generated by Django 2.2.5 on 2021-10-03 10:20
from datetime import timezone

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guardians_of_children', '0005_auto_20211003_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
        migrations.RemoveField(
            model_name='violence',
            name='title_1',
        ),
        migrations.RemoveField(
            model_name='violence',
            name='video_2',
        ),
        migrations.AddField(
            model_name='violence',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='violence',
            name='res',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='violence',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-10-03 06:00:00.000000-08:00'),
            preserve_default=False,
        ),
    ]
