# Generated by Django 2.2.5 on 2021-10-04 06:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guardians_of_children', '0007_remove_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default=datetime.datetime(2021, 10, 4, 6, 41, 59, 898119, tzinfo=utc), upload_to='video/%y'),
            preserve_default=False,
        ),
    ]
